Sprint 9 solution http api
LisaMorgunova/java-kanban pull request #10
Opened 2024-05-30 15:19 UTC by LisaMorgunova

working code

2024-05-30 19:55 UTC, z8q requested changes

2024-05-30 19:55 UTC, z8q commented on src/server/HttpTaskServer.java
> +    private static HttpServer server = null;
Можно не делать поле статическим, и перенести логику создания сервера в конструктор
this.server = HttpServer.create(...)
server.createContext(...)
...

В методе start оставить только логику запуска

2024-05-30 19:55 UTC, z8q commented on test/server/HttpTaskManagerHistoryTest.java
> +        String requestBody = "{\"name\": \"Task 1\", \"description\": \"Description 1\"}";
Можно создавать обычным образом, а потом, с помощью gson, переводить в строку с json

2024-05-30 19:55 UTC, z8q commented on src/server/HttpTaskServer.java
> +
Код, который идет ниже, похож на тестовые данные
Стоит перенести

2024-05-30 19:55 UTC, z8q commented on src/server/TaskHandler.java
> +        Task task = new Task("Task 1", "Description 1");
Идея в том, что мы получаем post-запрос на сохранение или обновление объекта.
Сам объект сидит в body у exchange, получить json можно так
new String(h.getRequestBody().readAllBytes(), StandardCharsets.UTF_8);
Далее с помощью gson переводим строку в объект, и потом идет отправка на сохранение или обновление.
Определять, какое действие совершать, можно по id. Если поле заполнено, обновляем задачу.
Если id отсутствует, значит выполняем операцию по созданию задачи

2024-05-30 19:55 UTC, z8q commented on src/server/SubTaskHandler.java
> +        return null;
Тут нужно дописать метод

2024-05-30 19:55 UTC, z8q commented on src/server/HttpTaskServer.java
> +    public static final Gson gson = new Gson();
Можно почитать еще про адаптеры, которые применяются к GsonBuilder, например для дат (LocalDateTime)

2024-05-30 19:55 UTC, z8q commented on src/server/PrioritizedHandler.java
> +        Gson gson = new Gson();
В некоторых хендлерах используем объект из HttpTaskServer, в некоторых создаем.
Можно привести к одному виду

2024-05-30 19:55 UTC, z8q commented on src/server/EpicHandler.java
> +    private String convertSubTasksToJson(List<SubTask> subtasks) {
Можно методы в строках 138-146 попробовать привести к одному методу, который принимает Object

2024-05-31 13:17 UTC, closed without merging

2024-05-31 13:19 UTC, LisaMorgunova commented
Fixed