Sprint 7
LisaMorgunova/java-kanban pull request #4
Opened 2024-03-22 08:22 UTC by LisaMorgunova

Добавлен новый класс FileBackedTaskManager и покрыт тестами

2024-03-22 18:04 UTC, z8q requested changes

2024-03-22 18:04 UTC, z8q commented on src/service/FileBackedTaskManager.java
> +    File save;
private final

2024-03-22 18:04 UTC, z8q commented on src/service/FileBackedTaskManager.java
> +            FW.write(historyToString(historyManager));
Сохраняется только история, нужно сохранять все состояние менеджера.
Все типы задач, которые менеджер создал, нужно тоже сохранять

2024-03-22 18:04 UTC, z8q commented on src/service/FileBackedTaskManager.java
> +            FW.write(historyToString(historyManager));
Если в методе будет несколько вызовов write, то лучше обернуть FileWriter в [BufferedWriter](https://stackoverflow.com/questions/12350248/java-difference-between-filewriter-and-bufferedwriter).

2024-03-22 18:04 UTC, z8q commented on src/service/FileBackedTaskManager.java
> +            }
При загрузке из файла, нужно заполнять мапы с тасками тоже

2024-03-22 18:04 UTC, z8q commented on src/service/FileBackedTaskManager.java
> +        return null;
Похоже метод не нужен.

Методы преобразования из/в строки можно вынести в отдельный класс

2024-03-22 18:04 UTC, z8q commented on src/model/Status.java
> +    static Status getType(String s) {
Тут есть несколько неплохих вариантов, как можно получить енам из сторки.
https://stackoverflow.com/questions/604424/how-to-get-an-enum-value-from-a-string-value-in-java

- через valueOf можно, но если нужного элемента нет, поймаем IllegalArgumentException
- через перебор элементов
- через предварительное создание мапы в static-блоке

2024-03-22 18:04 UTC, z8q commented on test/service/FileBackedTaskManagerTest.java
> +        assertTrue(historyManager.getHistory().containsAll(second.getHistory()));
В тесте можно еще проверить заполнение мап с задачами. 
Между созданиями менеджеров можно еще выполнить несколько операций чтения/записи.
После этого сравнить мапы первого и второго менеджера

2024-03-26 20:06 UTC, LisaMorgunova commented on src/service/FileBackedTaskManager.java
> +            FW.write(historyToString(historyManager));
Что ты имеешь ввиду под состоянием менеджера? Ведь состояние менеджера - это и есть история.

2024-03-31 18:39 UTC, closed without merging