Sprint 8 solution time and duration
LisaMorgunova/java-kanban pull request #7
Opened 2024-05-13 12:36 UTC by LisaMorgunova

Sprint 8 solution time and duration

2024-05-14 11:24 UTC, z8q requested changes

2024-05-14 11:24 UTC, z8q commented on src/service/InMemoryHistoryManager.java
>  public class InMemoryHistoryManager implements HistoryManager {
Мы же делали менеджер историй в этой [домашке](https://github.com/LisaMorgunova/java-kanban/pull/1/files#diff-ff889dfdbc2a19c447b09fc44f81e7bee5959a5624e7570722ae9b4b4329c794)
Со своим кастомным связным списком состоящим из нод.

Тут не нужен treeset и проверки на пересечения.

Проверки нужны в InMemoryTaskManager при добавлении и обновлении задач

2024-05-14 11:24 UTC, z8q commented on src/service/InMemoryTaskManager.java
В этом классе нужно создать new TreeSet<>(Comparator.comparing(Task::getStartTime));
И здесь добавить в методы add, update добавление тасок в этот список.
Стоит обратить внимание, что при обновлении задачи нужно сначала удалить ее из TreeSet и потом добавить заново, чтобы произошла сортировка.
В методах вида delete...   нужно также будет удалять задачи из TreeSet

2024-05-18 17:02 UTC, LisaMorgunova commented
Done

2024-05-18 17:02 UTC, closed without merging